
name: Tests

on: push

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    container: nilsleiffischer/gwpv:latest-dev
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python package
        run: |
          pip install -e .
      - name: Run unit tests
        run: |
          python -m unittest discover -s tests
      # TODO: Add sample data to test rendering example scenes
      - name: Run executable
        run: |
          gwrender.py -h
