
name: Tests

on: push

jobs:
  # These container builds don't pull caches from the Docker registry, so they
  # are very slow. Disabling them for now.
  # dev-container:
  #   name: Deploy dev-container
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: docker/build-push-action@v1
  #       with:
  #         dockerfile: containers/Dockerfile
  #         target: dev
  #         username: ${{ secrets.DOCKER_USERNAME }}
  #         password: ${{ secrets.DOCKER_PASSWORD }}
  #         repository: nilsleiffischer/gwpv
  #         # This would tag the container 'latest', not taking the build target
  #         # into account. So we tag the container 'latest-dev' manually, but
  #         # note that the container will be overridden by pushes to other
  #         # branches.
  #         # See: https://github.com/docker/build-push-action/issues/83
  #         # tag_with_ref: true
  #         tags: latest-dev
  #         always_pull: true
  #         cache_froms: nilsleiffischer/gwpv:latest-dev
  tests:
    name: Tests
    runs-on: ubuntu-latest
    # needs: dev-container
    container: nilsleiffischer/gwpv:latest-dev
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python package
        run: |
          pip install .
      - name: Run unit tests
        run: |
          python -m unittest discover -s tests
      - name: Setup rendering test
        run: |
          mkdir test_render
          cp Examples/Rainbow/Datasources.example.yaml test_render/Datasources.yaml
          sed -i -e 's/\/scratch\/example/./' test_render/Datasources.yaml
      - name: Download test data
        working-directory: test_render
        run: |
          wget https://zenodo.org/record/3321679/files/Lev3/rhOverM_Asymptotic_GeometricUnits_CoM.h5
      - name: Test 'scene' endpoint
        working-directory: test_render
        run: >
          gwrender.py scene
          ../Examples/Rainbow/Rainbow.yaml Resolutions/Test
          -p ./ -o ./dist -n2 -v --frame-window 0 4
      - name: Test 'scenes' endpoint
        working-directory: test_render
        run: >
          gwrender.py scenes
          ../Examples/Rainbow/Scenes.yaml Resolutions/Test
          -p ./ -o ./dist -n2 -v
      # - name: Test 'waveform' endpoint
      #   working-directory: test_render
      #   run: >
      #     gwrender.py waveform ../Examples/Rainbow/Rainbow.yaml
      #     --time-merger 5064 --mass 150 -p ./ -o ./dist -v
  # deploy-container:
  #   name: Deploy container
  #   needs: tests
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: docker/build-push-action@v1
  #       with:
  #         dockerfile: containers/Dockerfile
  #         username: ${{ secrets.DOCKER_USERNAME }}
  #         password: ${{ secrets.DOCKER_PASSWORD }}
  #         repository: nilsleiffischer/gwpv
  #         tag_with_ref: true
  #         cache_froms: nilsleiffischer/gwpv:latest-dev,nilsleiffischer/gwpv:latest
  #         always_pull: true
